name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 8']
    steps:
    - name: Force XCode 14.1
    - run: sudo xcode-select -switch /Applications/Xcode_14.1.app
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        set -o pipefail && \
        xcodebuild -project RadioPlus.xcodeproj \
        -scheme RadioPlusTests \
        -destination "${destination}" \
        test | xcpretty
      env:
        destination: ${{ matrix.destination }}
